{
 "title": "Modbus WB-M1W2 exporter",
 "description": "Temperature sensors",
 "tags": [
  "modbus",
  "temperature",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Exporter status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "modbus_up{instance=\"wb-modbus-controller\"}",
     "legendFormat": "status link"
    }
   ]
  },
  {
   "title": "Exporter memory usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"wb_modbus_temp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed polls total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "targets": [
    { "expr": "modbus_failed_polls_total", "legendFormat": "polls error" }
   ]
  },
  {
   "title": "Data age (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "modbus_data_age_seconds{instance=\"wb-modbus-controller\"}",
     "legendFormat": "sensor {{sensor}}"
    }
   ]
  },
  {
   "title": "Temperature sensors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "modbus_temperature{instance=\"wb-modbus-controller\", sensor=\"1\"}",
     "legendFormat": "Шкаф (s1)"
    },
    {
     "expr": "modbus_temperature{instance=\"wb-modbus-controller\", sensor=\"2\"}",
     "legendFormat": "Улица (s2)"
    }
   ]
  },
  {
   "title": "Last Update Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - modbus_last_update_timestamp{job=\"wb_modbus_temp\"}",
     "legendFormat": "sensor {{sensor}}"
    }
   ]
  },
  {
   "title": "Load CPU Exporter",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"wb_modbus_temp\"}[5m]) * 100",
     "legendFormat": "cpu_python"
    }
   ]
  }
 ]
}